version: '3'
services:
  dns:
    build: ./dns
    image: docker_open5gs_dns
    container_name: dns
    volumes:
      - ./dns:/mnt/dns
    expose:
      - "53/udp"
    networks:
      default:
        ipv4_address: ${DNS_IP}
  mysql:
    build: ./mysql
    image: open5gs_mysql
    container_name: mysql
    volumes:
      - ./mysql_db:/var/lib/mysql
      - ./mysql:/mnt/mysql
    networks:
      default:
        ipv4_address: ${MYSQL_IP}
  rtpengine:
    build: ./rtpengine
    image: open5gs_rtpengine
    privileged: true
    container_name: rtpengine
    volumes:
      - ./rtpengine:/mnt/rtpengine
    environment:
      - RTPENGINE_IP=${RTPENGINE_IP}
    networks:
      default:
        ipv4_address: ${RTPENGINE_IP}
  pcscf:
    build: ./pcscf
    image: docker_open5gs_pcscf
    container_name: pcscf
    privileged: true
    volumes:
      - ./pcscf:/mnt/pcscf
    depends_on:
      - dns
      - mysql
      - rtpengine
    environment:
      - MYSQL_IP=${MYSQL_IP}
      - RTPENGINE_IP=${RTPENGINE_IP}
      - PCSCF_IP=${PCSCF_IP}
    dns: ${DNS_IP}
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
    networks:
      default:
        ipv4_address: ${PCSCF_IP}
  icscf:
    build: ./icscf
    image: docker_open5gs_icscf
    container_name: icscf
    volumes:
      - ./icscf:/mnt/icscf
    depends_on:
      - dns
      - mysql
    environment:
      - MYSQL_IP=${MYSQL_IP}
      - ICSCF_IP=${ICSCF_IP}
      - FHOSS_IP=${FHOSS_IP}
    dns: ${DNS_IP}
    ports:
      - "4060:4060/tcp"
      - "4060:4060/udp"
    networks:
      default:
        ipv4_address: ${ICSCF_IP}
  scscf:
    build: ./scscf
    image: docker_open5gs_scscf
    container_name: scscf
    volumes:
      - ./scscf:/mnt/scscf
    depends_on:
      - dns
      - mysql
    environment:
      - MYSQL_IP=${MYSQL_IP}
      - SCSCF_IP=${SCSCF_IP}
      - FHOSS_IP=${FHOSS_IP}
    dns: ${DNS_IP}
    ports:
      - "6060:6060/tcp"
      - "6060:6060/udp"
    networks:
      default:
        ipv4_address: ${SCSCF_IP}
  fhoss:
    build: ./fhoss
    image: docker_open5gs_fhoss
    container_name: fhoss
    volumes:
      - ./fhoss:/mnt/fhoss
    depends_on:
      - dns
      - mysql
    environment:
      - MYSQL_IP=${MYSQL_IP}
      - FHOSS_IP=${FHOSS_IP}
    dns: ${DNS_IP}
    ports:
      - "8080:8080/tcp"
    networks:
      default:
        ipv4_address: ${FHOSS_IP}
networks:
  default:
    ipam:
      config:
        - subnet: ${SUBNET}
